payload:
  - DOMAIN-SUFFIX,thezion.club
  - DOMAIN-SUFFIX,ls.apple.com
  - DOMAIN-SUFFIX,guzzoni.apple.com
  - DOMAIN-SUFFIX,rehi.org
  - DST-PORT,123
  - IP-CIDR,172.96.252.0/22
  - IP-CIDR,104.194.91.0/22
# Tencent/Huawei Network
  - IP-ASN,132203
  - IP-ASN,55990
# China DNS
  - DOMAIN,dns.alidns.com
  - DOMAIN,dot.pub
