payload:
  - DOMAIN-KEYWORD,grammarly
  - DOMAIN-KEYWORD,surfshark
# Maylaysia
  - DOMAIN-SUFFIX,my
  - DOMAIN-KEYWORD,touchngo
  - DOMAIN-KEYWORD,celcom
# Netflix
  - DOMAIN-KEYWORD,netflix
  - DOMAIN-KEYWORD,nflx
  - DOMAIN-KEYWORD,flxvpn
  - DOMAIN-SUFFIX,online-metrix.net
# Disney+
  - DOMAIN-SUFFIX,comcast.net
  - DOMAIN-SUFFIX,dssedge.com
  - DOMAIN-SUFFIX,cqloud.com
  - DOMAIN-SUFFIX,footprint.net
  - DOMAIN-SUFFIX,service-now.com
  - DOMAIN-SUFFIX,hwcdn.net
# http3
  - DOMAIN-SUFFIX,cloudflare-quic.com
  - DOMAIN-SUFFIX,http3.is
  - DOMAIN-SUFFIX,nginx.org
  - DOMAIN-SUFFIX,quicwg.org
