payload:
  - DOMAIN-SUFFIX,ipleak.net
  - DOMAIN-SUFFIX,binance.com
  - DOMAIN-SUFFIX,huobi.pro
  - DOMAIN-SUFFIX,hbdm.com
  - DOMAIN-SUFFIX,hbdm.vn
  - DOMAIN-KEYWORD,huobi.com
  - DOMAIN-KEYWORD,htx.com
# Netflix
  - DOMAIN-KEYWORD,netflix
  - DOMAIN-KEYWORD,nflx
  - DOMAIN-KEYWORD,flxvpn
  - DOMAIN-SUFFIX,online-metrix.net
# Disney+
#  - DOMAIN-SUFFIX,comcast.net
#  - DOMAIN-SUFFIX,dssedge.com
#  - DOMAIN-SUFFIX,cqloud.com
#  - DOMAIN-SUFFIX,footprint.net
#  - DOMAIN-SUFFIX,service-now.com
#  - DOMAIN-SUFFIX,hwcdn.net
