payload:
  - DOMAIN-KEYWORD,grammarly
  - DOMAIN-KEYWORD,surfshark
# Maylaysia
  - DOMAIN-SUFFIX,my
  - DOMAIN-KEYWORD,touchngo
  - DOMAIN-KEYWORD,celcom
# http3
  - DOMAIN-SUFFIX,cloudflare-quic.com
  - DOMAIN-SUFFIX,http3.is
  - DOMAIN-SUFFIX,nginx.org
  - DOMAIN-SUFFIX,quicwg.org
# dns leak test
  - DOMAIN-SUFFIX,ipleak.net
